all: ex01 ex02 ex03 ex04 ex05 ex06 ex08 ex09 ex10

ex01:
	@echo "\e[32mTask 1\e[0m"
	@echo "1.0 2.0 3.0\n4.0 5.0 6.0" | python3 exercise1/task1.py

ex02:
	@echo "\e[32mTask 2\e[0m"
	@echo "1143411" | python3 exercise2/task2.py

ex03:
	@echo "\e[32mTask 3\e[0m"
	@python3 exercise3/task3.py

ex04:
	@echo "\e[32mTask 4\e[0m"
	@echo "5" | python3 exercise4/task4.py

ex05:
	@echo "\e[32mTask 5\e[0m"
	@echo "-14.97" | python3 exercise5/task5.py
	@echo "+19.2" | python3 exercise5/task5.py

ex07:
	@echo "\e[32mTask 7\e[0m"
	@echo "3 4\n3 0 2 1\n6 4 8 5\n3 3 6 0" | python3 exercise7/task7.py

ex06:
	@echo "\e[32mTask 6\e[0m"
	@python3 exercise6/task6.py

ex08:
	@echo "\e[32mTask 8\e[0m"
	@echo "10\n5\n3\n7\n3\n6\n3\n5\n2\n9\n4" | python3 exercise8/task8.py

ex09:
	@echo "\e[32mTask 9\e[0m"
	@echo "2 3.0\n5\n1.2\n-3" | python3 exercise9/task9.py

ex10:
	@echo "\e[32mTask 10\e[0m"
	@echo "5 48\n2023 100 14\n2020 18 347\n2023 10000000 34\n2023 1000 34\n2022 10 34\n" | python3 exercise10/task10.py


